/* Author: Jay Huang */

$(function() { 
  window.songlist = {
    "songs": [
      {"songname":"The Simpsons","artist":"Cartoon","id":1,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Barney & Friends","artist":"Kids","id":2,"file":"Goo Goo Dolls - Iris.mp3"},
      {"songname":"Banana Splits (Tra La La Song)","artist":"Kids","id":3,"file":"Goo Goo Dolls - Slide.mp3"},
      {"songname":"Flintstones","artist":"Cartoon","id":4,"file":"J-REYEZ - Our Promise.mp3"},
      {"songname":"Scooby Doo","artist":"Kids","id":5,"file":"Natalie Imbruglia - Torn.mp3"},
      {"songname":"Smurfs","artist":"Kids","id":6,"file":"NieR Gestalt & RepliCant - Repose.mp3"},
      {"songname":"Mister Rogers","artist":"Kids","id":7,"file":"One Republic - Counting Stars.mp3"},
      {"songname":"Mr Dressup","artist":"Kids","id":8,"file":"The Script - If You Could See Me Now.mp3"},
      {"songname":"Friendly Giant","artist":"kids","id":9,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Tranformers","artist":"Cartoon","id":10,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Teenage Mutant Ninja Turtles","artist":"Cartoon","id":11,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Gem","artist":"cartoon","id":12,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"The Electric Company","artist":"Kids","id":13,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Sesame Street","artist":"Kids","id":14,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Power Rangers","artist":"Kids","id":15,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Leave It To Beaver","artist":"Kids","id":16,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"The Muppet Show","artist":"Variety","id":17,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Saved By The Bell","artist":"Comedy","id":18,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Fresh Prince of Bel-Air","artist":"Comedy","id":19,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Beverly Hills 90210","artist":"Drama","id":20,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Silver Spoons (Together)","artist":"Comedy","id":21,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Home Improvement","artist":"Comedy","id":22,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Price Is Right","artist":"Game Show","id":23,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Bevis & Butthead","artist":"Cartoon","id":24,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"The Brady Bunch","artist":"Comedy","id":25,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Married With Children (Love & Marriage)","artist":"Comedy","id":26,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"The Partridge Family (Cmon Get Happy)","artist":"Comedy","id":27,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Fraggle Rock","artist":"Kids","id":28,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Littliest Hobo (Maybe Tommorow)","artist":"Kids","id":29,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Flipper","artist":"Kids","id":30,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Baywatch (Don't You Worry)","artist":"Drama","id":31,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Jeffersons (Moving On Up)","artist":"Comedy","id":32,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"All In The Family (Those Were The Days)","artist":"Comedy","id":33,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Roseanne","artist":"Comedy","id":34,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Seinfeld","artist":"Comedy","id":35,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Mork & Mindy","artist":"Comedy","id":36,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Laverne & Shirley (Doing It Our Way)","artist":"Comedy","id":37,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"It's A Different World","artist":"Comedy","id":38,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Friends (I'll Remember You)","artist":"Comedy","id":39,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"South Park","artist":"Comedy","id":40,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"WKRP In Cincinati","artist":"Comedy","id":41,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Happy Days","artist":"Comedy","id":42,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"M*A*S*H","artist":"Comedy","id":43,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Three's Company","artist":"Comedy","id":44,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Beachcombers","artist":"Drama","id":45,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"The Incredible Hulk","artist":"Drama","id":46,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Charlie's Angels","artist":"Crime/Drama","id":47,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Law & Order","artist":"Crime/Drama","id":48,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"ER","artist":"Drama","id":49,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Dallas","artist":"Drama","id":50,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"The Benny Hill Show","artist":"Comedy","id":51,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"The A Team","artist":"Crime/Drama","id":52,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"American Idol","artist":"Reality","id":53,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"CSI (Who Are You)","artist":"Crime/Drama","id":54,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Sex & The City","artist":"Drama","id":55,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Smallville (Save Me)","artist":"Drama","id":56,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Sopranos (Woke Up This Morning)","artist":"Drama","id":57,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Six Million Dollar Man","artist":"Drama","id":58,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Battlestar Galactica","artist":"Space","id":59,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Night Heat (I Feel)","artist":"Crime Drama","id":60,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"The Exorcist","artist":"Movie","id":61,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Halloween","artist":"Movie","id":62,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Superman The Movie","artist":"Movie","id":63,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Speed","artist":"Movie","id":64,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Flash Gordon","artist":"Movie","id":65,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Robocop","artist":"Movie","id":66,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"The Bad News Bears","artist":"Movie","id":67,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Monty Python & The Holy Grail","artist":"Movie","id":68,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"The Godfather","artist":"Movie","id":69,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"T2 (Terminator 2)","artist":"Movie","id":70,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"The Terminator","artist":"Movie","id":71,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"2001 A Space Odyssey","artist":"Movie","id":72,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"Chariots Of Fire","artist":"Movie","id":73,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"The Good The Bad & The ,Ugly","artist":"Movie","id":74,"file":"Final Fantasy X OST - To Zanarkand.mp3"},
      {"songname":"The Sting (The Entertainer)","artist":"Movie","id":75,"file":"Final Fantasy X OST - To Zanarkand.mp3"}
    ]
  }
});